import { useUsers } from '../../hooks/User'

export default function index() {
  const users = useUsers()

  return (
    <div>
      Autogenerated scaffold for page
      <pre>{JSON.stringify(users, null, 2)}</pre>
    </div>
  )
}
